### ISSUE TITLE
Package can't be installed from github

### ISSUE THREAD

**Issue by luyzdeleon** [pokt-network/pocket-aat-js#20]
**Describe the bug**
Package can't be installed from github

**To Reproduce**
`npm install --save pokt-network/pocket-aat-js#staging`

**Expected behavior**
The package must be correctly installed.

**Comment by pabelnl** [comment]
This issue must be related to the package.json pointing to 
  "main": "lib/src/pocket-aat.js",
  "types": "lib/src/pocket-aat.d.ts",

instead to the index.js and index.d.ts files inside lib/src/
